import { CustomerInterface } from '@state-management-app/types';
import { of } from 'rxjs';

export const MOCK_CUSTOMER: CustomerInterface = {
  customerId: '1',
  name: 'John',
  lastname: 'Doe',
  email: 'johndoe@email.com',
  username: 'johndoe',
  address: {
    addressId: '1',
    address: '123 Main St',
    latitude: '123',
    longitude: '123',
    notes: 'This is a note',
    tagName: '',
  },
  contactNumber: '1234567890',
  isLoggedIn: false,
  password: '123456',
  role: {
    roleId: '1',
    roleName: 'Customer',
  },
  userId: '1',
  deleted: false,
  picture: '',
  refreshToken: '',
};

export const MOCK_CUSTOMERS: CustomerInterface[] = [
  {
    customerId: '1',
    name: 'John',
    lastname: 'Doe',
    email: 'johndoe@email.com',
    username: 'johndoe',
    address: {
      addressId: '1',
      address: '123 Main St',
      latitude: '123',
      longitude: '123',
      notes: 'This is a note',
      tagName: '',
    },
    contactNumber: '1234567890',
    isLoggedIn: false,
    password: '123456',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '1',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '2',
    name: 'Jane',
    lastname: 'Smith',
    email: 'janesmith@email.com',
    username: 'janesmith',
    address: {
      addressId: '2',
      address: '456 Oak St',
      latitude: '456',
      longitude: '456',
      notes: 'This is another note',
      tagName: '',
    },
    contactNumber: '9876543210',
    isLoggedIn: false,
    password: '654321',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '2',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '3',
    name: 'Robert',
    lastname: 'Johnson',
    email: 'rjohnson@email.com',
    username: 'rjohnson',
    address: {
      addressId: '3',
      address: '789 Maple St',
      latitude: '789',
      longitude: '789',
      notes: 'This is a third note',
      tagName: '',
    },
    contactNumber: '5551234567',
    isLoggedIn: false,
    password: 'password1',
    role: {
      roleId: '2',
      roleName: 'Admin',
    },
    userId: '3',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '4',
    name: 'Samantha',
    lastname: 'Williams',
    email: 'swilliams@email.com',
    username: 'swilliams',
    address: {
      addressId: '4',
      address: '789 Elm St',
      latitude: '123',
      longitude: '456',
      notes: '',
      tagName: '',
    },
    contactNumber: '5559876543',
    isLoggedIn: false,
    password: 'password2',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '4',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '5',
    name: 'William',
    lastname: 'Johnson',
    email: 'wjohnson@email.com',
    username: 'wjohnson',
    address: {
      addressId: '5',
      address: '321 Cedar St',
      latitude: '456',
      longitude: '789',
      notes: '',
      tagName: '',
    },
    contactNumber: '5554567890',
    isLoggedIn: false,
    password: 'password3',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '5',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '6',
    name: 'Isabella',
    lastname: 'Clark',
    email: 'iclarke@email.com',
    username: 'iclarke',
    address: {
      addressId: '6',
      address: '246 Park Ave',
      latitude: '555',
      longitude: '666',
      notes: '',
      tagName: '',
    },
    contactNumber: '5551114444',
    isLoggedIn: false,
    password: 'password6',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '6',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '7',
    name: 'William',
    lastname: 'Thomas',
    email: 'wthomas@email.com',
    username: 'wthomas',
    address: {
      addressId: '7',
      address: '789 Lincoln St',
      latitude: '777',
      longitude: '888',
      notes: '',
      tagName: '',
    },
    contactNumber: '5552225555',
    isLoggedIn: false,
    password: 'password7',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '7',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '8',
    name: 'Emily',
    lastname: 'Gonzalez',
    email: 'egonzalez@email.com',
    username: 'egonzalez',
    address: {
      addressId: '8',
      address: '246 Main St',
      latitude: '999',
      longitude: '000',
      notes: 'A note about this address',
      tagName: '',
    },
    contactNumber: '5553336666',
    isLoggedIn: false,
    password: 'password8',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '8',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '9',
    name: 'Daniel',
    lastname: 'Rodriguez',
    email: 'drodriguez@email.com',
    username: 'drodriguez',
    address: {
      addressId: '9',
      address: '753 Elm St',
      latitude: '111',
      longitude: '222',
      notes: '',
      tagName: '',
    },
    contactNumber: '5554447777',
    isLoggedIn: false,
    password: 'password9',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '9',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '10',
    name: 'Ava',
    lastname: 'Lopez',
    email: 'alopez@email.com',
    username: 'alopez',
    address: {
      addressId: '10',
      address: '135 1st Ave',
      latitude: '333',
      longitude: '444',
      notes: '',
      tagName: '',
    },
    contactNumber: '5557774444',
    isLoggedIn: false,
    password: 'password10',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '10',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '11',
    name: 'Gabriel',
    lastname: 'García',
    email: 'ggarcia@email.com',
    username: 'ggarcia',
    address: {
      addressId: '11',
      address: '246 5th Ave',
      latitude: '111',
      longitude: '222',
      notes: '',
      tagName: '',
    },
    contactNumber: '5554443333',
    isLoggedIn: false,
    password: 'password11',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '11',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '12',
    name: 'Laura',
    lastname: 'Lee',
    email: 'llee@email.com',
    username: 'llee',
    address: {
      addressId: '12',
      address: '789 Broadway',
      latitude: '333',
      longitude: '444',
      notes: 'A note about this address',
      tagName: '',
    },
    contactNumber: '5557778888',
    isLoggedIn: false,
    password: 'password12',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '12',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '13',
    name: 'Oliver',
    lastname: 'Davis',
    email: 'odavis@email.com',
    username: 'odavis',
    address: {
      addressId: '13',
      address: '135 4th St',
      latitude: '555',
      longitude: '666',
      notes: '',
      tagName: '',
    },
    contactNumber: '5552223333',
    isLoggedIn: false,
    password: 'password13',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '13',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '14',
    name: 'Sophia',
    lastname: 'Wilson',
    email: 'swilson@email.com',
    username: 'swilson',
    address: {
      addressId: '14',
      address: '246 Elm St',
      latitude: '777',
      longitude: '888',
      notes: '',
      tagName: '',
    },
    contactNumber: '5558889999',
    isLoggedIn: false,
    password: 'password14',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '14',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
  {
    customerId: '15',
    name: 'Ethan',
    lastname: 'Brown',
    email: 'ebrown@email.com',
    username: 'ebrown',
    address: {
      addressId: '15',
      address: '753 Oak St',
      latitude: '999',
      longitude: '000',
      notes: 'A note about this address',
      tagName: '',
    },
    contactNumber: '5551112222',
    isLoggedIn: false,
    password: 'password15',
    role: {
      roleId: '1',
      roleName: 'Customer',
    },
    userId: '15',
    deleted: false,
    picture: '',
    refreshToken: '',
  },
];

export const activatedRouteMock = {
  params: of({ customerId: '1' }),
};
